# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-06 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=11, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('avatar', models.ImageField(upload_to='', verbose_name='头像')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
